USE [master]
GO

/****** Object:  Database [RpaAlmDev]    Script Date: 1/13/2026 8:22:44 AM ******/
DROP DATABASE IF EXISTS [RpaAlmDev]
GO

/****** Object:  Database [RpaAlmDev]    Script Date: 1/13/2026 8:22:44 AM ******/
CREATE DATABASE [RpaAlmDev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RpaAlmDev', FILENAME = N'F:\MSSQL2016\MSSQL13.MSSQLSERVER\MSSQL\Data\RpaAlmDev.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RpaAlmDev_log', FILENAME = N'G:\MSSQL2016\MSSQL13.MSSQLSERVER\MSSQL\Log\RpaAlmDev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 --WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF --2019+ ?
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RpaAlmDev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RpaAlmDev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RpaAlmDev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RpaAlmDev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RpaAlmDev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RpaAlmDev] SET ARITHABORT OFF 
GO

ALTER DATABASE [RpaAlmDev] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [RpaAlmDev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RpaAlmDev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RpaAlmDev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RpaAlmDev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RpaAlmDev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RpaAlmDev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RpaAlmDev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RpaAlmDev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RpaAlmDev] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RpaAlmDev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RpaAlmDev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RpaAlmDev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RpaAlmDev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RpaAlmDev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RpaAlmDev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RpaAlmDev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RpaAlmDev] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RpaAlmDev] SET  MULTI_USER 
GO

ALTER DATABASE [RpaAlmDev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RpaAlmDev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RpaAlmDev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RpaAlmDev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RpaAlmDev] SET DELAYED_DURABILITY = DISABLED 
GO

--ALTER DATABASE [RpaAlmDev] SET ACCELERATED_DATABASE_RECOVERY = OFF  --2019 and later
--GO

ALTER DATABASE [RpaAlmDev] SET OPTIMIZED_LOCKING = OFF 
GO

ALTER DATABASE [RpaAlmDev] SET QUERY_STORE = ON
GO

ALTER DATABASE [RpaAlmDev] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [RpaAlmDev] SET  READ_WRITE 
GO

